{{- if .Values.traefik.ssl.defaultcrt }}
apiVersion: v1
data:
   tls.crt: {{ .Values.traefik.ssl.defaultcrt }}
   tls.key: {{ .Values.traefik.ssl.defaultkey }}
kind: Secret
metadata:
  name: public-cert
type: Opaque
{{- end }}
